eqfeed_callback({
	"type":"FeatureCollection",
	"features":[
		{
			"type":"Feature",
			"properties":{
				"mag":12,
				"place":"La Verne",
				"id":49
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7678,34.1008]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":43,
				"place":"Sunland",
				"id":90
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3083,34.2596]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":24,
				"place":"Victoria Park",
				"id":191
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3319,34.0470]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":91,
				"place":"Redondo Beach",
				"id":72
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3884,33.8492]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":154,
				"place":"South Gate",
				"id":83
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2120,33.9547]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":114,
				"place":"Norwalk",
				"id":127
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0817,33.9022]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":28,
				"place":"Century City",
				"id":16
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4134,34.0537]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":14,
				"place":"Santa Fe Springs",
				"id":211
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0853,33.9472]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":114,
				"place":"West Hollywood",
				"id":107
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3617,34.0900]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":51,
				"place":"Arleta",
				"id":135
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4338,34.2505]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Jefferson Park",
				"id":215
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3176,34.0272]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":94,
				"place":"Pico Rivera",
				"id":120
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0967,33.9831]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"South El Monte",
				"id":82
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0467,34.0520]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":82,
				"place":"Pomona",
				"id":136
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7500,34.0551]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":16,
				"place":"Gramercy Place",
				"id":192
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3319,34.0470]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":58,
				"place":"Bell Gardens",
				"id":137
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1515,33.9653]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":31,
				"place":"Harvard Heights",
				"id":129
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3042,34.0422]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":15,
				"place":"Playa Vista",
				"id":70
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4192,33.9754]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":26,
				"place":"Vermont Knolls",
				"id":100
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2893,33.9273]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Signal Hill",
				"id":213
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1678,33.8045]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":30,
				"place":"West Hills",
				"id":106
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6440,34.1973]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":25,
				"place":"Los Feliz",
				"id":56
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2848,34.1063]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":46,
				"place":"Westchester",
				"id":110
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3988,33.9626]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":28,
				"place":"Beverlywood",
				"id":8
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3952,34.0494]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":192,
				"place":"Palmdale",
				"id":66
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1165,34.5794]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":71,
				"place":"Whittier",
				"id":113
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0328,33.9792]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":63,
				"place":"South Park",
				"id":84
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2740,33.9965]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":26,
				"place":"Agoura Hills",
				"id":0
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.7617,34.1533]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":33,
				"place":"Glendora",
				"id":38
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8653,34.1361]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":80,
				"place":"Glassell Park",
				"id":138
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2334,34.1090]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":11,
				"place":"Park La Brea",
				"id":69
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3552,34.0700]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":45,
				"place":"Mar Vista",
				"id":59
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4338,34.0153]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":25,
				"place":"Bel Air",
				"id":157
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4595,34.1002]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":48,
				"place":"Valley Glen",
				"id":97
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4138,34.1867]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":111,
				"place":"Reseda",
				"id":73
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5361,34.2011]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":33,
				"place":"Pacific Palisades",
				"id":65
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5156,34.0356]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":221,
				"place":"Santa Clarita",
				"id":77
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5426,34.3917]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":29,
				"place":"Lakeview Terrace",
				"id":184
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3612,34.2764]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":25,
				"place":"Vermont Square",
				"id":193
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3002,34.0037]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Rancho Park",
				"id":197
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4207,34.0454]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":62,
				"place":"West Covina",
				"id":105
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9390,34.0686]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":109,
				"place":"Panorama City",
				"id":141
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4424,34.2276]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":127,
				"place":"Westlake",
				"id":111
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.8074,34.1466]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":48,
				"place":"Chatsworth",
				"id":158
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6148,34.2506]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":457,
				"place":"Long Beach",
				"id":118
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1937,33.7701]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":32,
				"place":"Duarte",
				"id":27
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9773,34.1395]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":100,
				"place":"Pacoima",
				"id":144
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4105,34.2768]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":41,
				"place":"Westwood",
				"id":112
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4455,34.0635]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":65,
				"place":"Wilshire Center",
				"id":115
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3004,34.0654]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":24,
				"place":"Diamond Bar",
				"id":25
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8103,34.0286]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":51,
				"place":"Highland Park",
				"id":126
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-87.8003,42.1817]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":124,
				"place":"Santa Monica",
				"id":78
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4912,34.0195]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":31,
				"place":"Beverly Crest",
				"id":159
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4163,34.1013]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":111,
				"place":"West Vernon",
				"id":109
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2802,34.0053]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":13,
				"place":"Cheviot Hills",
				"id":182
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4042,34.0403]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":74,
				"place":"Bellflower",
				"id":6
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1170,33.8817]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":50,
				"place":"Watts",
				"id":140
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2380,33.9386]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":24,
				"place":"Temple City",
				"id":194
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0578,34.1072]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":33,
				"place":"Hyde Park",
				"id":44
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3306,33.9806]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":249,
				"place":"Melrose",
				"id":60
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3550,34.0837]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":78,
				"place":"Huntington Park",
				"id":178
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2251,33.9817]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":44,
				"place":"Baldwin Park",
				"id":185
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9609,34.0853]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":90,
				"place":"Woodland Hills",
				"id":117
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6090,34.1654]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":11,
				"place":"Thai Town",
				"id":201
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3036,34.1018]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":17,
				"place":"Rosemead",
				"id":179
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0728,34.0806]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Marina Peninsula",
				"id":190
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4657,33.9797]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":23,
				"place":"Azusa",
				"id":160
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9076,34.1336]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":23,
				"place":"Malibu",
				"id":161
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.7798,34.0259]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":52,
				"place":"Hollywood Hills",
				"id":43
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3520,34.1177]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":59,
				"place":"Brentwood",
				"id":10
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4732,34.0521]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":80,
				"place":"Palms",
				"id":67
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4075,34.0244]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":78,
				"place":"Koreatown",
				"id":46
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3009,34.0597]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":16,
				"place":"Claremont",
				"id":124
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7198,34.0967]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":106,
				"place":"Hawthorne",
				"id":41
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3526,33.9164]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":17,
				"place":"Cloverdale/Cochran",
				"id":19
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-119.5604,36.0980]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":39,
				"place":"San Fernando",
				"id":75
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4390,34.2819]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":30,
				"place":"South Pasadena",
				"id":85
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1503,34.1161]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":46,
				"place":"Little Bangladesh",
				"id":146
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2969,34.0691]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":36,
				"place":"Palos Verdes Estates",
				"id":163
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3901,33.8006]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":16,
				"place":"Adams-Normandie",
				"id":186
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2993,34.0343]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":39,
				"place":"Wholesale District",
				"id":125
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2326,34.0419]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Reynier Village",
				"id":206
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3856,34.0368]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Hawaiian Gardens",
				"id":164
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0728,33.8314]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Commerce",
				"id":216
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1598,34.0006]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":30,
				"place":"Arcadia",
				"id":3
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0353,34.1397]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":63,
				"place":"Central",
				"id":165
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3228,34.0687]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":72,
				"place":"Vernon Central",
				"id":102
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2565,34.0039]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":73,
				"place":"Exposition Park",
				"id":34
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2862,34.0149]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":141,
				"place":"Burbank",
				"id":11
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3090,34.1808]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":20,
				"place":"Monrovia",
				"id":149
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0019,34.1443]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"View Heights",
				"id":214
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3477,33.9844]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":82,
				"place":"San Pedro",
				"id":76
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2922,33.7361]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":89,
				"place":"Temple-Beaudry",
				"id":166
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2513,34.0629]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":30,
				"place":"La Canada Flintridge",
				"id":47
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2000,34.2068]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":97,
				"place":"Boyle Heights",
				"id":9
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2117,34.0298]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":61,
				"place":"Sun Valley",
				"id":89
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3813,34.2279]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":37,
				"place":"La Mirada",
				"id":48
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0120,33.9172]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":73,
				"place":"Winnetka",
				"id":116
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5740,34.2049]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":59,
				"place":"Manhattan Beach",
				"id":58
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4109,33.8847]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":69,
				"place":"West Adams",
				"id":104
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3627,34.0325]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":41,
				"place":"Baldwin Hills",
				"id":5
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3404,34.0182]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":61,
				"place":"El Monte",
				"id":183
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0276,34.0686]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":42,
				"place":"Mission Hills",
				"id":180
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4689,34.2723]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":13,
				"place":"Echo Park",
				"id":31
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2606,34.0782]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Toluca Lake",
				"id":198
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3550,34.1502]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":40,
				"place":"Cerritos",
				"id":18
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0648,33.8583]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":16,
				"place":"Atwater Village",
				"id":202
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2614,34.1173]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":50,
				"place":"Harvard Park",
				"id":167
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3043,33.9837]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":215,
				"place":"Pasadena",
				"id":119
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1445,34.1478]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":146,
				"place":"Hollywood",
				"id":42
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3287,34.0928]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":58,
				"place":"Hancock Park",
				"id":40
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3287,34.0723]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Shadow Hills",
				"id":195
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3550,34.2575]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":30,
				"place":"Green Meadows",
				"id":187
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2694,33.9556]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":93,
				"place":"Sherman Oaks",
				"id":80
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4514,34.1490]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":13,
				"place":"Rolling Hills Estates",
				"id":196
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3581,33.7878]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":49,
				"place":"Rancho Palos Verdes",
				"id":71
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3870,33.7445]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":47,
				"place":"Alhambra",
				"id":1
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1270,34.0953]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":31,
				"place":"Historic Filipinotown",
				"id":189
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2680,34.0703]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"St Elmo Village",
				"id":219
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3430,34.0431]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Cadillac-Corning",
				"id":212
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2437,34.0522]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":43,
				"place":"West Los Angeles",
				"id":108
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4426,34.0412]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":142,
				"place":"Van Nuys",
				"id":98
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4514,34.1899]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":42,
				"place":"Maywood",
				"id":152
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1853,33.9867]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":21,
				"place":"Hermosa Beach",
				"id":168
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3995,33.8622]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Lafayette Square",
				"id":203
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3319,34.0431]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":65,
				"place":"Little Armenia",
				"id":199
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.300497,34.098114]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":10,
				"place":"Artesia",
				"id":169
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0831,33.8658]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":30,
				"place":"Lincoln Heights",
				"id":54
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2118,34.0737]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"San Marino",
				"id":170
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1065,34.1214]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":25,
				"place":"Studio City",
				"id":88
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3871,34.1396]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":30,
				"place":"Mid-city",
				"id":172
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3287,34.0416]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":29,
				"place":"Calabasas",
				"id":12
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6615,34.1367]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":52,
				"place":"Carthay",
				"id":173
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3680,34.0558]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":31,
				"place":"Harbor City",
				"id":153
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2965,33.7907]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":43,
				"place":"Monterey Park",
				"id":62
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1228,34.0625]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":16,
				"place":"Walnut",
				"id":103
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8653,34.0203]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":22,
				"place":"Mt. Washington",
				"id":130
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2204,34.0992]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":33,
				"place":"Country Club Park",
				"id":188
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3212,34.0503]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":123,
				"place":"Canoga Park",
				"id":13
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6059,34.2083]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":93,
				"place":"Bell",
				"id":154
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1870,33.9775]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":69,
				"place":"Granada Hills",
				"id":39
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5022,34.2794]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":43,
				"place":"Harbor Gateway",
				"id":131
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3024,33.8405]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Manchester Square",
				"id":220
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2977,33.8993]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":103,
				"place":"Lynwood",
				"id":57
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2115,33.9303]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":56,
				"place":"Tarzana",
				"id":92
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5506,34.1495]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":52,
				"place":"Valley Village",
				"id":174
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3842,34.1633]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":132,
				"place":"Lancaster",
				"id":52
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1542,34.6868]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":36,
				"place":"Lawndale",
				"id":53
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3526,33.8872]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":19,
				"place":"San Gabriel",
				"id":132
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1058,34.0961]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":184,
				"place":"North Hollywood",
				"id":63
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3813,34.1870]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":177,
				"place":"Inglewood",
				"id":45
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3531,33.9617]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":63,
				"place":"Florence-Firestone",
				"id":175
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2436,33.9672]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":163,
				"place":"Carson",
				"id":14
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2817,33.8317]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":75,
				"place":"North Hills",
				"id":151
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4849,34.2358]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":137,
				"place":"Downey",
				"id":133
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1332,33.9401]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":63,
				"place":"Encino",
				"id":33
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5214,34.1517]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":29,
				"place":"Miracle Mile",
				"id":61
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3491,34.0595]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Wellington Square",
				"id":217
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3343,34.0392]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Elysian Park",
				"id":200
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2366,34.0838]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":45,
				"place":"Vermont Vista",
				"id":101
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2827,33.9455]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":204,
				"place":"Torrance",
				"id":94
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3406,33.8358]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":35,
				"place":"Crenshaw District",
				"id":142
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3404,34.0182]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":40,
				"place":"Culver City",
				"id":23
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3965,34.0211]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":80,
				"place":"Paramount",
				"id":68
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1598,33.8895]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":56,
				"place":"Lakewood",
				"id":51
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1340,33.8536]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":38,
				"place":"University Park",
				"id":96
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2790,34.0310]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":58,
				"place":"Eagle Rock",
				"id":28
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2141,34.1392]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":30,
				"place":"Cudahy",
				"id":176
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1858,33.9609]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":20,
				"place":"El Segundo",
				"id":32
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4165,33.9192]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":92,
				"place":"Silverlake",
				"id":81
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2702,34.0869]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":12,
				"place":"Alsace",
				"id":207
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4156,33.9786]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":171,
				"place":"Sylmar",
				"id":91
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4572,34.3058]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":34,
				"place":"Downtown",
				"id":26
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2468,34.0407]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":39,
				"place":"Porter Ranch",
				"id":123
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5506,34.2822]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":72,
				"place":"East Hollywood",
				"id":29
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2936,34.0913]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":30,
				"place":"Tujunga",
				"id":95
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3083,34.2596]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":51,
				"place":"Crestview",
				"id":22
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.9826,37.7495]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":50,
				"place":"Lake Balboa",
				"id":50
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7678,34.1008]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":40,
				"place":"Del Rey",
				"id":24
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4249,33.9860]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":23,
				"place":"San Dimas",
				"id":74
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8067,34.1067]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":115,
				"place":"Compton",
				"id":20
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2201,33.8958]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":55,
				"place":"Wilmington",
				"id":114
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2644,33.7858]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":107,
				"place":"Gardena",
				"id":36
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3090,33.8883]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":46,
				"place":"Century Palms/Cove",
				"id":17
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2732,33.9453]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":15,
				"place":"Figueroa Park Square",
				"id":204
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2840,33.9602]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":10,
				"place":"Reseda Ranch",
				"id":208
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5356,34.2160]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Longwood",
				"id":218
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2037,33.8670]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":56,
				"place":"El Sereno",
				"id":181
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1786,34.0736]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":339,
				"place":"Glendale",
				"id":37
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2551,34.1425]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":87,
				"place":"Northridge",
				"id":64
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5301,34.2381]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":40,
				"place":"Venice",
				"id":99
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4695,33.9850]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":27,
				"place":"Lomita",
				"id":55
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3151,33.7922]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":113,
				"place":"Pico-Union",
				"id":162
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2892,34.0443]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":63,
				"place":"Covina",
				"id":21
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8903,34.0900]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":25,
				"place":"Leimert Park",
				"id":155
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3235,34.0107]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":21,
				"place":"South Carthay",
				"id":177
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3734,34.0561]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":12,
				"place":"Elysian Valley",
				"id":210
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2427,34.0967]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":94,
				"place":"Beverly Hills",
				"id":7
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4004,34.0736]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":22,
				"place":"La Puente",
				"id":134
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9495,34.0200]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":80,
				"place":"Montebello",
				"id":156
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1138,34.0165]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Westlake Village",
				"id":209
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.8074,34.1466]
			}
		}
	]
});
