eqfeed_callback({
	"type":"FeatureCollection",
	"features":[
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Diamond Bar"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8103,34.0286]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Venice"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4695,33.9850]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"West Vernon"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2802,34.0053]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"North Hollywood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3813,34.1870]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Inglewood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3531,33.9617]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Santa Monica"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4912,34.0195]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Walnut"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8653,34.0203]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Carson"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2817,33.8317]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Reseda"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5361,34.2011]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Pasadena"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1445,34.1478]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":10,
				"place":"Melrose"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3550,34.0837]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Encino"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5214,34.1517]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Hollywood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3287,34.0928]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Woodland Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6090,34.1654]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Torrance"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3406,33.8358]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Culver City"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3965,34.0211]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Hollywood Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3520,34.1177]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Brentwood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4732,34.0521]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Sherman Oaks"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4514,34.1490]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Koreatown"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3009,34.0597]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Alhambra"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1270,34.0953]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Eagle Rock"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2141,34.1392]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"South Pasadena"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1503,34.1161]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"West Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6440,34.1973]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Silverlake"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2702,34.0869]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"West Los Angeles"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4426,34.0412]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Sylmar"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4572,34.3058]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Arcadia"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0353,34.1397]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"San Dimas"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8067,34.1067]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Mar Vista"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4338,34.0153]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Gardena"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3090,33.8883]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Century Palms/Cove"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2732,33.9453]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"San Pedro"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2922,33.7361]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Manhattan Beach"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4109,33.8847]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Glendale"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2551,34.1425]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Northridge"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5301,34.2381]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Monterey Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1228,34.0625]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Westchester"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3988,33.9626]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Santa Clarita"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5426,34.3917]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":11,
				"place":"West Hollywood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3617,34.0900]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Boyle Heights"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2117,34.0298]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Beverly Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4004,34.0736]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Granada Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5022,34.2794]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Long Beach"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1937,33.7701]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"La Mirada"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0120,33.9172]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Lynwood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2115,33.9303]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Tarzana"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5506,34.1495]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"West Adams"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3627,34.0325]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Baldwin Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3404,34.0182]
			}
		}
	]
});
