eqfeed_callback({
	"type":"FeatureCollection",
	"features":[
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Diamond Bar",
				"id":25
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8103,34.0286]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Santa Monica",
				"id":78
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4912,34.0195]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"West Vernon",
				"id":109
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2802,34.0053]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"North Hollywood",
				"id":63
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3813,34.1870]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Inglewood",
				"id":45
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3531,33.9617]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Venice",
				"id":99
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4695,33.9850]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Carson",
				"id":14
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2817,33.8317]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Reseda",
				"id":73
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5361,34.2011]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Pasadena",
				"id":119
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1445,34.1478]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Melrose",
				"id":60
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3550,34.0837]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Encino",
				"id":33
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5214,34.1517]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Hollywood",
				"id":42
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3287,34.0928]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Woodland Hills",
				"id":117
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6090,34.1654]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Torrance",
				"id":94
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3406,33.8358]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Culver City",
				"id":23
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3965,34.0211]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Hollywood Hills",
				"id":43
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3520,34.1177]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Brentwood",
				"id":10
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4732,34.0521]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Sherman Oaks",
				"id":80
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4514,34.1490]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Koreatown",
				"id":46
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3009,34.0597]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Alhambra",
				"id":1
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1270,34.0953]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Eagle Rock",
				"id":28
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2141,34.1392]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"South Pasadena",
				"id":85
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1503,34.1161]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"West Hills",
				"id":106
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6440,34.1973]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Silverlake",
				"id":81
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2702,34.0869]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Westchester",
				"id":110
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3988,33.9626]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Arcadia",
				"id":3
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0353,34.1397]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Altadena",
				"id":2
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1313,34.1902]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"San Dimas",
				"id":74
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8067,34.1067]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Mar Vista",
				"id":59
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4338,34.0153]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Gardena",
				"id":36
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3090,33.8883]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"San Pedro",
				"id":76
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2922,33.7361]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Glendale",
				"id":37
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2551,34.1425]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Northridge",
				"id":64
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5301,34.2381]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Monterey Park",
				"id":62
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1228,34.0625]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Tarzana",
				"id":92
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5506,34.1495]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Santa Clarita",
				"id":77
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5426,34.3917]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"West Hollywood",
				"id":107
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3617,34.0900]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Boyle Heights",
				"id":9
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2117,34.0298]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Beverly Hills",
				"id":7
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4004,34.0736]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Granada Hills",
				"id":39
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5022,34.2794]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Long Beach",
				"id":118
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1937,33.7701]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"La Mirada",
				"id":48
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0120,33.9172]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Lynwood",
				"id":57
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2115,33.9303]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Manhattan Beach",
				"id":58
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4109,33.8847]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"West Adams",
				"id":104
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3627,34.0325]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Baldwin Hills",
				"id":5
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3404,34.0182]
			}
		}
	]
});
