eqfeed_callback({
	"type":"FeatureCollection",
	"features":[
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"La Verne",
				"id":49
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7678,34.1008]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Sunland",
				"id":90
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3083,34.2596]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Redondo Beach",
				"id":72
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3884,33.8492]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"South Gate",
				"id":83
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2120,33.9547]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Century City",
				"id":16
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4134,34.0537]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Glendora",
				"id":38
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8653,34.1361]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":31,
				"place":"West Hollywood",
				"id":107
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3617,34.0900]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Arleta",
				"id":135
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4338,34.2505]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Pico Rivera",
				"id":120
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0967,33.9831]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"South El Monte",
				"id":82
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0467,34.0520]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Pomona",
				"id":136
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7500,34.0551]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Bell Gardens",
				"id":137
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1515,33.9653]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Playa Vista",
				"id":70
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4192,33.9754]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Vermont Knolls",
				"id":100
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2893,33.9273]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Stevenson Ranch",
				"id":87
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5908,34.3931]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"South Pasadena",
				"id":85
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1503,34.1161]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Willowbrook",
				"id":121
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-87.9359,41.7698]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Los Feliz",
				"id":56
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2848,34.1063]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Walnut",
				"id":103
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8653,34.0203]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Westchester",
				"id":110
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3988,33.9626]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Beverlywood",
				"id":8
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3952,34.0494]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Canyon Country",
				"id":122
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4721,34.4235]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Whittier",
				"id":113
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0328,33.9792]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"South Park",
				"id":84
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2740,33.9965]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Agoura Hills",
				"id":0
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.7617,34.1533]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Glassell Park",
				"id":138
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2334,34.1090]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Park La Brea",
				"id":69
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3552,34.0700]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Mar Vista",
				"id":59
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4338,34.0153]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":11,
				"place":"Valley Glen",
				"id":97
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4138,34.1867]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Reseda",
				"id":73
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5361,34.2011]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Pacific Palisades",
				"id":65
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5156,34.0356]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":10,
				"place":"Santa Clarita",
				"id":77
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5426,34.3917]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"West Covina",
				"id":105
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9390,34.0686]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Westlake",
				"id":111
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.8074,34.1466]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":28,
				"place":"Long Beach",
				"id":118
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1937,33.7701]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Duarte",
				"id":27
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9773,34.1395]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Valinda",
				"id":139
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9431,34.0453]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Westwood",
				"id":112
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4455,34.0635]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Wilshire Center",
				"id":115
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3004,34.0654]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Castaic",
				"id":15
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6257,34.4890]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Diamond Bar",
				"id":25
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8103,34.0286]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Santa Monica Mountains",
				"id":79
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.9318,34.1203]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":18,
				"place":"Santa Monica",
				"id":78
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4912,34.0195]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Vermont Vista",
				"id":101
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2827,33.9455]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"West Vernon",
				"id":109
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2802,34.0053]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Bellflower",
				"id":6
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1170,33.8817]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Watts",
				"id":140
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2380,33.9386]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Hancock Park",
				"id":40
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3287,34.0723]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Hyde Park",
				"id":44
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3306,33.9806]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":33,
				"place":"Melrose",
				"id":60
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3550,34.0837]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":11,
				"place":"Woodland Hills",
				"id":117
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6090,34.1654]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Hollywood Hills",
				"id":43
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3520,34.1177]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":34,
				"place":"Brentwood",
				"id":10
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4732,34.0521]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Palms",
				"id":67
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4075,34.0244]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Koreatown",
				"id":46
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3009,34.0597]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Claremont",
				"id":124
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7198,34.0967]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Hawthorne",
				"id":41
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3526,33.9164]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Cloverdale/Cochran",
				"id":19
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-119.5604,36.0980]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"San Fernando",
				"id":75
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4390,34.2819]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Downtown",
				"id":26
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2468,34.0407]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Wholesale District",
				"id":125
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2326,34.0419]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Highland Park",
				"id":126
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-87.8003,42.1817]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Arcadia",
				"id":3
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0353,34.1397]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Vernon Central",
				"id":102
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2565,34.0039]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Exposition Park",
				"id":34
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2862,34.0149]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Burbank",
				"id":11
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3090,34.1808]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"San Pedro",
				"id":76
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2922,33.7361]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"La Canada Flintridge",
				"id":47
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2000,34.2068]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Boyle Heights",
				"id":9
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2117,34.0298]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Sun Valley",
				"id":89
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3813,34.2279]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"La Mirada",
				"id":48
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0120,33.9172]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Winnetka",
				"id":116
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5740,34.2049]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"South Whittier",
				"id":86
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0403,33.9510]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":17,
				"place":"Manhattan Beach",
				"id":58
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4109,33.8847]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"West Adams",
				"id":104
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3627,34.0325]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Baldwin Hills",
				"id":5
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3404,34.0182]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Norwalk",
				"id":127
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0817,33.9022]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Alhambra",
				"id":1
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1270,34.0953]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Cerritos",
				"id":18
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0648,33.8583]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Pasadena",
				"id":119
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1445,34.1478]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":23,
				"place":"Hollywood",
				"id":42
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3287,34.0928]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Temple",
				"id":93
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0578,34.1072]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Rancho Palos Verdes",
				"id":71
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3870,33.7445]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Echo Park",
				"id":31
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2606,34.0782]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"West Hills",
				"id":106
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6440,34.1973]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"West Los Angeles",
				"id":108
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4426,34.0412]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Van Nuys",
				"id":98
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4514,34.1899]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Altadena",
				"id":2
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1313,34.1902]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Studio City",
				"id":88
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3871,34.1396]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Pico",
				"id":128
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-79.6948,37.4982]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Calabasas",
				"id":12
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6615,34.1367]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Monterey Park",
				"id":62
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1228,34.0625]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Harvard Heights",
				"id":129
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3042,34.0422]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Mt. Washington",
				"id":130
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2204,34.0992]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Canoga Park",
				"id":13
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6059,34.2083]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Panorama City",
				"id":141
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4424,34.2276]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Palmdale",
				"id":66
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1165,34.5794]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Granada Hills",
				"id":39
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5022,34.2794]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Harbor Gateway",
				"id":131
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3024,33.8405]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Lynwood",
				"id":57
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2115,33.9303]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Tarzana",
				"id":92
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5506,34.1495]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Florence",
				"id":35
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2481,33.9745]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":13,
				"place":"Lancaster",
				"id":52
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1542,34.6868]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Lawndale",
				"id":53
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3526,33.8872]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"San Gabriel",
				"id":132
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1058,34.0961]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":11,
				"place":"North Hollywood",
				"id":63
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3813,34.1870]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Inglewood",
				"id":45
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3531,33.9617]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Athens",
				"id":4
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2812,33.9200]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Carson",
				"id":14
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2817,33.8317]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Downey",
				"id":133
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1332,33.9401]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":13,
				"place":"Encino",
				"id":33
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5214,34.1517]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Miracle Mile",
				"id":61
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3491,34.0595]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Torrance",
				"id":94
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3406,33.8358]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Crenshaw District",
				"id":142
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3404,34.0182]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Culver City",
				"id":23
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3965,34.0211]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Northridge",
				"id":64
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5301,34.2381]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Lakewood",
				"id":51
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1340,33.8536]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"University Park",
				"id":96
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2790,34.0310]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Eagle Rock",
				"id":28
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2141,34.1392]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Venice",
				"id":99
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4695,33.9850]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"El Segundo",
				"id":32
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4165,33.9192]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Silverlake",
				"id":81
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2702,34.0869]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Sylmar",
				"id":91
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4572,34.3058]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Porter Ranch",
				"id":123
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5506,34.2822]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"East Hollywood",
				"id":29
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2936,34.0913]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Tujunga",
				"id":95
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3083,34.2596]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Crestview",
				"id":22
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.9826,37.7495]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Lake Balboa",
				"id":50
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7678,34.1008]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Del Rey",
				"id":24
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4249,33.9860]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"San Dimas",
				"id":74
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8067,34.1067]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Compton",
				"id":20
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2201,33.8958]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Wilmington",
				"id":114
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2644,33.7858]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Gardena",
				"id":36
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3090,33.8883]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Century Palms/Cove",
				"id":17
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2732,33.9453]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":12,
				"place":"Glendale",
				"id":37
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2551,34.1425]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Paramount",
				"id":68
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1598,33.8895]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Lomita",
				"id":55
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3151,33.7922]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"East Los Angeles",
				"id":30
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1670,34.0224]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Covina",
				"id":21
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8903,34.0900]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":12,
				"place":"Sherman Oaks",
				"id":80
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4514,34.1490]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":13,
				"place":"Beverly Hills",
				"id":7
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4004,34.0736]
			}
		}
	]
});
