eqfeed_callback({
	"type":"FeatureCollection",
	"features":[
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"La Verne"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7678,34.1008]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Sunland"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3083,34.2596]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":20,
				"place":"Redondo Beach"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3884,33.8492]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"South Gate"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2120,33.9547]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Century City"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4134,34.0537]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Glendora"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8653,34.1361]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":35,
				"place":"West Hollywood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3617,34.0900]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Arleta"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4338,34.2505]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Pico Rivera"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0967,33.9831]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"South El Monte"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0467,34.0520]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Pomona"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7500,34.0551]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Bell Gardens"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1515,33.9653]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Playa Vista"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4192,33.9754]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Vermont Central"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2919,34.0700]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Vermont Knolls"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2893,33.9273]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Stevenson Ranch"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5908,34.3931]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"South Pasadena"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1503,34.1161]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Willowbrook"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-87.9359,41.7698]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Los Feliz"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2848,34.1063]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Walnut"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8653,34.0203]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Westchester"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3988,33.9626]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":10,
				"place":"Beverlywood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3952,34.0494]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Canyon Country"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4721,34.4235]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Whittier"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0328,33.9792]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"South Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2740,33.9965]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Agoura Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.7617,34.1533]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Glassell Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2334,34.1090]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Park La Brea"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3552,34.0700]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Mar Vista"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4338,34.0153]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":12,
				"place":"Valley Glen"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4138,34.1867]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Reseda"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5361,34.2011]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":12,
				"place":"Pacific Palisades"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5156,34.0356]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":16,
				"place":"Santa Clarita"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5426,34.3917]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"West Covina"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9390,34.0686]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Westlake"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.8074,34.1466]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Duarte"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9773,34.1395]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Pacoima"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4105,34.2768]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Valinda"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9431,34.0453]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"West Whittier/Los Nietos"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0679,33.9801]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":11,
				"place":"Westwood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4455,34.0635]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Wilshire Center"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3004,34.0654]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Castaic"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6257,34.4890]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Diamond Bar"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8103,34.0286]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Santa Monica Mountains"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.9318,34.1203]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":21,
				"place":"Santa Monica"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4912,34.0195]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Vermont Vista"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2827,33.9455]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"West Vernon"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2802,34.0053]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Bellflower"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1170,33.8817]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Watts"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2380,33.9386]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":10,
				"place":"Hancock Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3287,34.0723]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Hyde Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3306,33.9806]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":47,
				"place":"Melrose"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3550,34.0837]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":13,
				"place":"Woodland Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6090,34.1654]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":17,
				"place":"Hollywood Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3520,34.1177]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":42,
				"place":"Brentwood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4732,34.0521]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":10,
				"place":"Palms"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4075,34.0244]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Koreatown"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3009,34.0597]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Claremont"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7198,34.0967]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Hawthorne"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3526,33.9164]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Cloverdale/Cochran"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-119.5604,36.0980]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"San Fernando"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4390,34.2819]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Downtown"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2468,34.0407]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Little Bangladesh"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2969,34.0691]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Wholesale District"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2326,34.0419]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Highland Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-87.8003,42.1817]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Arcadia"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0353,34.1397]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Chatworth"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6148,34.2506]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Azuza"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9076,34.1336]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Exposition Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2862,34.0149]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Burbank"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3090,34.1808]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Monrovia"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0019,34.1443]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"San Pedro"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2922,33.7361]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Hacienda Heights"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9687,33.9931]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"La Canada Flintridge"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2000,34.2068]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Boyle Heights"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2117,34.0298]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Sun Valley"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3813,34.2279]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"North Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4849,34.2358]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Winnetka"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5740,34.2049]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"South Whittier"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0403,33.9510]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":21,
				"place":"Manhattan Beach"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4109,33.8847]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"West Adams"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3627,34.0325]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Baldwin Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3404,34.0182]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Norwalk"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0817,33.9022]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Alhambra"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1270,34.0953]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Cerritos"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0648,33.8583]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":27,
				"place":"Hollywood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3287,34.0928]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Temple"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0578,34.1072]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":17,
				"place":"Sherman Oaks"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4514,34.1490]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Rancho Palos Verdes"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3870,33.7445]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Echo Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2606,34.0782]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"West Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6440,34.1973]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"West Los Angeles"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4426,34.0412]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Van Nuys"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4514,34.1899]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Maywood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1853,33.9867]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Altadena"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1313,34.1902]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Lincoln Heights"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2118,34.0737]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":11,
				"place":"Studio City"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3871,34.1396]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Pico"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-79.6948,37.4982]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Calabasas"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6615,34.1367]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Harbor City"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2965,33.7907]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Monterey Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1228,34.0625]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Harvard Heights"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3042,34.0422]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Mt. Washington"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2204,34.0992]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Canoga Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.6059,34.2083]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Bell"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1870,33.9775]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Palmdale"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1165,34.5794]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Granada Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5022,34.2794]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Harbor Gateway"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3024,33.8405]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"Lynwood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2115,33.9303]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":14,
				"place":"Tarzana"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5506,34.1495]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Florence"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2481,33.9745]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":16,
				"place":"Lancaster"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1542,34.6868]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Lawndale"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3526,33.8872]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"San Gabriel"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1058,34.0961]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":15,
				"place":"North Hollywood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3813,34.1870]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":12,
				"place":"Inglewood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3531,33.9617]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Athens"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2812,33.9200]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":21,
				"place":"Carson"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2817,33.8317]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":10,
				"place":"Downey"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1332,33.9401]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":21,
				"place":"Encino"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5214,34.1517]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":13,
				"place":"Miracle Mile"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3491,34.0595]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":14,
				"place":"Torrance"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3406,33.8358]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Crenshaw District"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3404,34.0182]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":8,
				"place":"Culver City"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3965,34.0211]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Northridge"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5301,34.2381]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":7,
				"place":"Lakewood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1340,33.8536]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":6,
				"place":"University Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2790,34.0310]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Eagle Rock"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2141,34.1392]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":11,
				"place":"Venice"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4695,33.9850]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"El Segundo"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4165,33.9192]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":11,
				"place":"Silverlake"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2702,34.0869]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Sylmar"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4572,34.3058]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Porter Ranch"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.5506,34.2822]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"East Hollywood"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2936,34.0913]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Tujunga"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3083,34.2596]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"La Mirada"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.0120,33.9172]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Crestview"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.9826,37.7495]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Lake Balboa"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.7678,34.1008]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":9,
				"place":"Del Rey"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4249,33.9860]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"San Dimas"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8067,34.1067]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Compton"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2201,33.8958]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":5,
				"place":"Wilmington"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2644,33.7858]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Gardena"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3090,33.8883]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":3,
				"place":"Century Palms/Cove"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2732,33.9453]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":23,
				"place":"Glendale"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.2551,34.1425]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Paramount"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1598,33.8895]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":12,
				"place":"Lomita"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3151,33.7922]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"East Los Angeles"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1670,34.0224]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":4,
				"place":"Covina"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.8903,34.0900]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":2,
				"place":"Leimert Park"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.3235,34.0107]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":15,
				"place":"Beverly Hills"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.4004,34.0736]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"La Puente"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-117.9495,34.0200]
			}
		},
		{
			"type":"Feature",
			"properties":{
				"mag":1,
				"place":"Montebello"
			},
			"geometry":{
				"type":"Point",
				"coordinates":[-118.1138,34.0165]
			}
		}
	]
});
